# Generated by Django 5.2.10 on 2026-01-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
