# Generated by Django 5.2.10 on 2026-01-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_ladies_special',
            field=models.BooleanField(default=False),
        ),
    ]
